name: Hello-World
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - run: echo Hello, World!
